# Generated by Django 5.1.6 on 2025-03-03 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='current_passage_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='practice.test'),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.readingpassage'),
        ),
    ]
