# Generated by Django 5.1.6 on 2025-03-04 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_practicesession_current_passage_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_group__order', 'order_number']},
        ),
        migrations.AlterModelOptions(
            name='questiongroup',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='specific_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='practice.questiongroup'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='questiongroup',
            unique_together={('passage', 'question_type')},
        ),
    ]
