# Generated by Django 5.1.6 on 2025-03-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_alter_question_options_alter_questiongroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='diagram_image',
            field=models.ImageField(blank=True, null=True, upload_to='diagram_images/'),
        ),
    ]
