# Generated by Django 5.1.6 on 2025-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_question_diagram_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='diagram_image',
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='diagram_image',
            field=models.ImageField(blank=True, null=True, upload_to='diagram_images/'),
        ),
    ]
