# Generated by Django 5.1.6 on 2025-03-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_remove_question_diagram_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='table_text',
            field=models.TextField(blank=True, help_text='CSV-formatted table data with {{qX}} placeholders for questions', null=True),
        ),
    ]
