# Generated by Django 5.1.6 on 2025-03-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_questiongroup_table_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='unique_options_only',
            field=models.BooleanField(default=False, help_text='If True, each option can be chosen only once in this question group'),
        ),
    ]
